server.port=9000
spring.config.import=file:./.env[.properties]

spring.application.name=eMedical

spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/emedical}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000

jwt.private.key=${JWT_SECRET}
jwt.key.expiration=${JWT_EXPIRATION}